/** Mirrors public/scripts/tokenizers.js's `tokenizers` enum exactly. */
export const tokenizers = {
    NONE: 0,
    GPT2: 1,
    OPENAI: 2,
    LLAMA: 3,
    NERD: 4,
    NERD2: 5,
    API_CURRENT: 6,
    MISTRAL: 7,
    YI: 8,
    API_TEXTGENERATIONWEBUI: 9,
    API_KOBOLD: 10,
    CLAUDE: 11,
    LLAMA3: 12,
    GEMMA: 13,
    JAMBA: 14,
    QWEN2: 15,
    COMMAND_R: 16,
    NEMO: 17,
    DEEPSEEK: 18,
    COMMAND_A: 19,
    BEST_MATCH: 99,
    // Registry entries (src/tokenizer-sources.js), from 1000 up, above upstream's range. A value is
    // fixed forever once shipped: never renumbered, reused or removed.
    QWEN3: 1000,
    LLAMA3_1: 1001,
    NEMO_TEKKEN: 1002,
    KIMI: 1003,
    QWEN2_VL: 1004,
    QWEN2_5: 1005,
    QWEN3_5: 1006,
    QWEN3_5_BASE: 1007,
    QWEN3_8: 1008,
    CODEQWEN1_5: 1009,
    DEEPSEEK_V2: 1010,
    DEEPSEEK_V2_5: 1011,
    DEEPSEEK_R1: 1012,
    DEEPSEEK_V3_1: 1013,
    DEEPSEEK_V3_2: 1014,
    DEEPSEEK_V4: 1015,
    DEEPSEEK_V4_1: 1016,
    DEEPSEEK_R1_DISTILL_QWEN: 1017,
    DEEPSEEK_R1_DISTILL_LLAMA: 1018,
    DEEPSEEK_R1_0528_QWEN3: 1019,
    GEMMA_4: 1020,
    GEMMA_4_ASSISTANT: 1021,
    GEMMA_3_IT: 1022,
    GEMMA_3_PT: 1023,
    GEMMA_3N: 1024,
    CODEGEMMA: 1025,
    GEMMA_2_JPN: 1026,
    LLAMA3_1_BASE: 1027,
    LLAMA3_3: 1028,
    LLAMA4: 1029,
    LLAMA_GUARD_3_8B: 1030,
    LLAMA_GUARD_3_11B_VISION: 1031,
    LLAMA_GUARD_2: 1032,
    LLAMA_GUARD_4: 1033,
    MISTRAL_7B_V0_3: 1034,
    MATHSTRAL: 1035,
    MISTRAL_LARGE_2411: 1036,
    MISTRAL_7B_V0_3_HF: 1037,
    CODESTRAL_22B_HF: 1038,
    CODESTRAL_MAMBA_HF: 1039,
    MATHSTRAL_HF: 1040,
    MISTRAL_LARGE_2411_HF: 1041,
    MINISTRAL_8B_2410_HF: 1042,
    MINISTRAL_3_INSTRUCT_HF: 1043,
    MINISTRAL_3_BASE_HF: 1044,
    MISTRAL_SMALL_4_HF: 1045,
    SHIELDSTRAL_HF: 1046,
    MISTRAL_SMALL_3_HF: 1047,
    COMMAND_A_VISION: 1048,
    COMMAND_A_PLUS: 1049,
    AYA_VISION_32B: 1050,
    TINY_AYA: 1051,
    TINY_AYA_BASE: 1052,
    COMMAND_R_08_2024_HF: 1053,
    AYA_VISION_32B_HF: 1054,
    GLM_4_0414: 1055,
    GLM_4_5: 1056,
    GLM_5: 1057,
    GLM_EDGE: 1058,
    AUTOGLM_PHONE: 1059,
    KIMI_K2_BASE: 1060,
    KIMI_K2_THINKING: 1061,
    KIMI_K2_5: 1062,
    KIMI_K3: 1063,
    KIMI_VL: 1064,
    MOONLIGHT: 1065,
    MINIMAX_TEXT_01: 1066,
    MINIMAX_M1: 1067,
    MINIMAX_M2: 1068,
    MINIMAX_M3: 1069,
    GPT_OSS: 1070,
};

/**
 * Numeric tokenizer enum -> string key used by encodeTextByLocalTokenizerType() and the
 * '/api/tokenizers/<key>/encode' routes. Derived from the string segment of each entry's `encode`
 * URL in public/scripts/tokenizers.js's TOKENIZER_URLS. Only covers tokenizer types that have a
 * local encoder (i.e. every ENCODE_TOKENIZERS entry, plus CLAUDE, GPT2, NERD and NERD2, which also
 * have real local encoders even though they're not in ENCODE_TOKENIZERS - that list is about the
 * UI's encode/decode playground, not about what's locally encodable).
 *
 * A registry value's key is instead its src/tokenizer-sources.js entry id, which has no local type
 * or route of its own.
 */
export const TOKENIZER_TYPE_KEYS = {
    [tokenizers.GPT2]: 'gpt2',
    [tokenizers.LLAMA]: 'llama',
    [tokenizers.NERD]: 'nerdstash',
    [tokenizers.NERD2]: 'nerdstash_v2',
    [tokenizers.MISTRAL]: 'mistral',
    [tokenizers.YI]: 'yi',
    [tokenizers.CLAUDE]: 'claude',
    [tokenizers.LLAMA3]: 'llama3',
    [tokenizers.GEMMA]: 'gemma',
    [tokenizers.JAMBA]: 'jamba',
    [tokenizers.QWEN2]: 'qwen2',
    [tokenizers.COMMAND_R]: 'command-r',
    [tokenizers.COMMAND_A]: 'command-a',
    [tokenizers.NEMO]: 'nemo',
    [tokenizers.DEEPSEEK]: 'deepseek',
    [tokenizers.QWEN3]: 'qwen3',
    [tokenizers.LLAMA3_1]: 'llama3.1',
    [tokenizers.NEMO_TEKKEN]: 'nemo-tekken',
    [tokenizers.KIMI]: 'kimi',
    [tokenizers.QWEN2_VL]: 'qwen2-vl',
    [tokenizers.QWEN2_5]: 'qwen2.5',
    [tokenizers.QWEN3_5]: 'qwen3.5',
    [tokenizers.QWEN3_5_BASE]: 'qwen3.5-base',
    [tokenizers.QWEN3_8]: 'qwen3.8',
    [tokenizers.CODEQWEN1_5]: 'codeqwen1.5',
    [tokenizers.DEEPSEEK_V2]: 'deepseek-v2',
    [tokenizers.DEEPSEEK_V2_5]: 'deepseek-v2.5',
    [tokenizers.DEEPSEEK_R1]: 'deepseek-r1',
    [tokenizers.DEEPSEEK_V3_1]: 'deepseek-v3.1',
    [tokenizers.DEEPSEEK_V3_2]: 'deepseek-v3.2',
    [tokenizers.DEEPSEEK_V4]: 'deepseek-v4',
    [tokenizers.DEEPSEEK_V4_1]: 'deepseek-v4.1',
    [tokenizers.DEEPSEEK_R1_DISTILL_QWEN]: 'deepseek-r1-distill-qwen',
    [tokenizers.DEEPSEEK_R1_DISTILL_LLAMA]: 'deepseek-r1-distill-llama',
    [tokenizers.DEEPSEEK_R1_0528_QWEN3]: 'deepseek-r1-0528-qwen3',
    [tokenizers.GEMMA_4]: 'gemma-4',
    [tokenizers.GEMMA_4_ASSISTANT]: 'gemma-4-assistant',
    [tokenizers.GEMMA_3_IT]: 'gemma-3-it',
    [tokenizers.GEMMA_3_PT]: 'gemma-3-pt',
    [tokenizers.GEMMA_3N]: 'gemma-3n',
    [tokenizers.CODEGEMMA]: 'codegemma',
    [tokenizers.GEMMA_2_JPN]: 'gemma-2-jpn',
    [tokenizers.LLAMA3_1_BASE]: 'llama3.1-base',
    [tokenizers.LLAMA3_3]: 'llama3.3',
    [tokenizers.LLAMA4]: 'llama4',
    [tokenizers.LLAMA_GUARD_3_8B]: 'llama-guard-3-8b',
    [tokenizers.LLAMA_GUARD_3_11B_VISION]: 'llama-guard-3-11b-vision',
    [tokenizers.LLAMA_GUARD_2]: 'llama-guard-2',
    [tokenizers.LLAMA_GUARD_4]: 'llama-guard-4',
    [tokenizers.MISTRAL_7B_V0_3]: 'mistral-7b-v0.3',
    [tokenizers.MATHSTRAL]: 'mathstral',
    [tokenizers.MISTRAL_LARGE_2411]: 'mistral-large-2411',
    [tokenizers.MISTRAL_7B_V0_3_HF]: 'mistral-7b-v0.3-hf',
    [tokenizers.CODESTRAL_22B_HF]: 'codestral-22b-hf',
    [tokenizers.CODESTRAL_MAMBA_HF]: 'codestral-mamba-hf',
    [tokenizers.MATHSTRAL_HF]: 'mathstral-hf',
    [tokenizers.MISTRAL_LARGE_2411_HF]: 'mistral-large-2411-hf',
    [tokenizers.MINISTRAL_8B_2410_HF]: 'ministral-8b-2410-hf',
    [tokenizers.MINISTRAL_3_INSTRUCT_HF]: 'ministral-3-instruct-hf',
    [tokenizers.MINISTRAL_3_BASE_HF]: 'ministral-3-base-hf',
    [tokenizers.MISTRAL_SMALL_4_HF]: 'mistral-small-4-hf',
    [tokenizers.SHIELDSTRAL_HF]: 'shieldstral-hf',
    [tokenizers.MISTRAL_SMALL_3_HF]: 'mistral-small-3-hf',
    [tokenizers.COMMAND_A_VISION]: 'command-a-vision',
    [tokenizers.COMMAND_A_PLUS]: 'command-a-plus',
    [tokenizers.AYA_VISION_32B]: 'aya-vision-32b',
    [tokenizers.TINY_AYA]: 'tiny-aya',
    [tokenizers.TINY_AYA_BASE]: 'tiny-aya-base',
    [tokenizers.COMMAND_R_08_2024_HF]: 'command-r-08-2024-hf',
    [tokenizers.AYA_VISION_32B_HF]: 'aya-vision-32b-hf',
    [tokenizers.GLM_4_0414]: 'glm-4-0414',
    [tokenizers.GLM_4_5]: 'glm-4.5',
    [tokenizers.GLM_5]: 'glm-5',
    [tokenizers.GLM_EDGE]: 'glm-edge',
    [tokenizers.AUTOGLM_PHONE]: 'autoglm-phone',
    [tokenizers.KIMI_K2_BASE]: 'kimi-k2-base',
    [tokenizers.KIMI_K2_THINKING]: 'kimi-k2-thinking',
    [tokenizers.KIMI_K2_5]: 'kimi-k2.5',
    [tokenizers.KIMI_K3]: 'kimi-k3',
    [tokenizers.KIMI_VL]: 'kimi-vl',
    [tokenizers.MOONLIGHT]: 'moonlight',
    [tokenizers.MINIMAX_TEXT_01]: 'minimax-text-01',
    [tokenizers.MINIMAX_M1]: 'minimax-m1',
    [tokenizers.MINIMAX_M2]: 'minimax-m2',
    [tokenizers.MINIMAX_M3]: 'minimax-m3',
    [tokenizers.GPT_OSS]: 'gpt-oss',
};
